dict ={}
name1=input("Enter the name of first friend : ")
lang1=input("Enter their favourite language : ")
dict.update({name1 : lang1})
name2=input("Enter the name of second friend : ")
lang2=input("Enter their favourite language : ")
dict.update({name2 : lang2})
name3=input("Enter the name of third friend : ")
lang3=input("Enter their favourite language : ")
dict.update({name3 : lang3})
name4=input("Enter the name of fourth friend : ")
lang4=input("Enter their favourite language : ")
dict.update({name4 : lang4})
print(dict)