num=[]
num1= int(input("Enter the first number : "))
num.append(num1)
num2= int(input("Enter the second number : "))
num.append(num2)
num3= int(input("Enter the third number : "))
num.append(num3)
num4=int( input("Enter the fourth number : "))
num.append(num4)
print(sum(num))
